function startGUI()
    % Startup window size is the same as main_GUI
    fig = uifigure('Name','Across Time And Space','Position',[100 100 1210 750]);

    
    bg = imread('startimage.jpg');

    % Create uiaxes display background image
    ax = uiaxes(fig, ...
        'Position', [0 0 1210 750], ...
        'XColor', 'none', ...
        'YColor', 'none', ...
        'Box', 'off');
    axis(ax, 'off');
    image(ax, [0 1], [0 1], bg);
    ax.XLim = [0 1];
    ax.YLim = [0 1];
    ax.XTick = [];
    ax.YTick = [];
    axis(ax, 'off');

    uistack(ax, 'bottom');

    % Title
    uilabel(fig, ...
    'Text', 'Across Time And Space', ...
    'FontSize', 32, ...
    'FontWeight', 'bold', ...
    'FontColor', [0.1 0.7 0.6], ...
    'HorizontalAlignment', 'center', ...
    'Position', [50 580 1110 50]);
    %uilabel(fig, ...
    %'Text', 'FROM MULTI-TEMPORAL SATELLITE IMAGES', ...
    %'FontSize', 32, ...
    %'FontWeight', 'bold', ...
    %'FontColor', [0.1 0.7 0.6], ...
    %'HorizontalAlignment', 'center', ...
    %'Position', [50 530 1110 50]);



    % Member's name 
    uilabel(fig, ...
    'Text', 'Group 15: M. Zhang, J. Zhu, B. Zhang', ...
    'FontSize', 18, ...
    'FontColor', [1 0.8 0], ...  
    'HorizontalAlignment', 'center', ...
    'Position', [405 500 400 30]);

     uilabel(fig, ...
    'Text', 'Y. Zhang, Y. Zhang, S. Li', ...
    'FontSize', 18, ...
    'FontColor', [1 0.8 0], ...  
    'HorizontalAlignment', 'center', ...
    'Position', [405 470 400 30]);

    % ‘Enter the system’ button
    uibutton(fig, ...
    'Text', 'Enter', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.1 0.7 0.6], ...   
    'FontColor', [1 1 1], ...               
    'Position', [535 350 140 50], ...
    'Tooltip', 'Click to launch the application', ...
    'ButtonPushedFcn', @(btn,event)enterMainApp(fig));

    %% Add QR Code Image 
    qrImg = imread('githubQRcode.png');  
    qrAxes = uiaxes(fig, ...
        'Position', [1030 30 150 150], ...  
        'XColor', 'none', 'YColor', 'none', ...
        'Box', 'off');
    axis(qrAxes, 'off');
    image(qrAxes, qrImg);
    qrAxes.XLim = [0 size(qrImg, 2)];
    qrAxes.YLim = [0 size(qrImg, 1)];
    uistack(qrAxes, 'top');

    %% Add Description for QR Code 
    uilabel(fig, ...
        'Text', 'Scan to visit our GitHub page', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ... 
        'FontColor', [1 0.5 0], ...
        'HorizontalAlignment', 'center', ...
        'Position', [1000 15 210 20]);
end

function enterMainApp(startupFig)
    main_GUI();
    pause(0.2); 
    drawnow;  
    close(startupFig);    
              
                
             
end
