function startGUI()
    % Startup window size is the same as main_GUI
    fig = uifigure('Name','VISUALIZING ENVIRONMENTAL CHANGE FROM MULTI-TEMPORAL SATELLITE IMAGES','Position',[100 100 1210 750]);

    
    bg = imread('startimage.jpg');

    % Create uiaxes display background image
    ax = uiaxes(fig, ...
        'Position', [0 0 1210 750], ...
        'XColor', 'none', ...
        'YColor', 'none', ...
        'Box', 'off');
    axis(ax, 'off');
    image(ax, [0 1], [0 1], bg);
    ax.XLim = [0 1];
    ax.YLim = [0 1];
    ax.XTick = [];
    ax.YTick = [];
    axis(ax, 'off');

    uistack(ax, 'bottom');

    % Title
    uilabel(fig, ...
    'Text', 'VISUALIZING ENVIRONMENTAL CHANGE FROM MULTI-TEMPORAL SATELLITE IMAGES', ...
    'FontSize', 26, ...
    'FontWeight', 'bold', ...
    'FontColor', [0.1 0.7 0.6], ...  % Farbe
    'HorizontalAlignment', 'center', ...
    'Position', [50 550 1110 50]);



    % Member's name 
    uilabel(fig, ...
    'Text', 'Project members: M. Zhang, J. Zhu, B. Zhang', ...
    'FontSize', 18, ...
    'FontColor', [1 0.8 0], ...  % Farbe
    'HorizontalAlignment', 'center', ...
    'Position', [405 500 400 30]);

     uilabel(fig, ...
    'Text', 'Y. Zhang, Y. Zhang, S. Li', ...
    'FontSize', 18, ...
    'FontColor', [1 0.8 0], ...  
    'HorizontalAlignment', 'center', ...
    'Position', [405 470 400 30]);

    % ‘Enter the system’ button
    uibutton(fig, ...
    'Text', 'Enter', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.1 0.7 0.6], ...   
    'FontColor', [1 1 1], ...               
    'Position', [535 350 140 50], ...
    'Tooltip', 'Click to launch the application', ...
    'ButtonPushedFcn', @(btn,event)enterMainApp(fig));
end

function enterMainApp(startupFig)
    main_GUI();          
    drawnow;              
    pause(0.2);           
    close(startupFig);    
end
